### ISSUE TITLE
Observable Viewmodel uses the same techniques (ObsFromEvent) as https://github.com/typebytes/ngx-template-streams (ObservableEvent)?

### ISSUE THREAD

**Issue by HansS** [SanderElias/Samples#1]

**Comment by SanderElias** [comment]
Hi @HansS 

No, it's using just a decorator and doesn't include a custom compiler that executes before the Angular compiler. ngx-template-streams is very experimental. My decorator is just exisitng available angular API's and will fork for both VE as wwell as ivy.
