### ISSUE TITLE
dynamichtml 

### ISSUE THREAD

**Issue by IgorMinar** [SanderElias/Samples#14]
Hi Sander,

I came across this dynamichtml example code and noticed that it [uses `innerHTML`](https://github.com/SanderElias/Samples/blob/db82b829c9cc494ceab43171f2b637ec0862504b/src/app/dynamichtml/dynamichtml.component.ts#L75) to insert new html into the DOM.

`innerHTML` is a source of security vulnerabilities and headaches. Can you please consider updating the example to use [`DOMSanitizer`](https://angular.io/api/platform-browser/DomSanitizer) to secure the content before it's inserted into the DOM?

thanks

**Comment by SanderElias** [comment]
Hi @IgorMinar 
Thanks for your concern. I wrote this sample on request, and it uses innerHTML on purpose. I did give proper verbal warnings about this 
But you are right, I will add at least some warnings, and will update the code to reflect the possible security concerns.
I will try to address this this week

The repo is called "samples" for a reason ;)

**Comment by IgorMinar** [comment]
Thanks for the consideration. `innerHTML` is such powerful API, but with power also comes responsibility, and unfortunately most people are not aware. This is why innerHTML is one of the APIs that will require special handling in applications that turn on Trusted Types - this will make the security risks more obvious.

Using the DOMSanitizer is easy and in most legit cases it doesn't affect the functionality or visuals of the content being inlined.

**Comment by SanderElias** [comment]
@IgorMinar I updated the sample.  
I hope I made it clear enough like this ;)

**Comment by IgorMinar** [comment]
Thank you!
